fn_single_line = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
format_macro_matchers = true
max_width = 80
use_small_heuristics = "Max"
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
# group_imports = StdExternalCrate # not stable, has bugs
struct_field_align_threshold = 16
tab_spaces = 2
use_field_init_shorthand = true
wrap_comments = true
